package com.dtos.response.cloudinary;

/**
 * Data Transfer Object holding Cloudinary signed upload credentials.
 * Issued by the server to allow the client app to upload media directly to Cloudinary storage.
 *
 * @param signature cryptographic HMAC signature string generated by backend credentials
 * @param timestamp epoch timestamp in seconds corresponding to signature generation
 * @param apiKey Cloudinary account API key
 * @param cloudName target Cloudinary account storage cloud name
 * @author Yaron Serlin
 * @version 1.0
 * @since 02/08/2026
 */
public record CloudinarySignatureResponse(
        String signature,
        long timestamp,
        String apiKey,
        String cloudName
) {
}
