/**
 * Shared DTO-layer component of the Cloudinary image-upload feature. Defines the response shape
 * {@code CloudinaryController.getSignature} returns and the Android client's
 * {@code CloudinaryUploader} consumes to authorize a direct-to-Cloudinary upload without the
 * client ever holding the account's API secret.
 */
package com.dtos.response.cloudinary;

/**
 * Data Transfer Object holding Cloudinary signed upload credentials.
 * Issued by the server to allow the client app to upload media directly to Cloudinary storage.
 *
 * @param signature cryptographic HMAC signature string generated by backend credentials
 * @param timestamp epoch timestamp in seconds corresponding to signature generation
 * @param apiKey Cloudinary account API key
 * @param cloudName target Cloudinary account storage cloud name
 * @author Yaron Serlin
 * @version 1.0
 * @since 02/08/2026
 */
public record CloudinarySignatureResponse(
        String signature,
        long timestamp,
        String apiKey,
        String cloudName
) {
}
