package com.cooksync_server.services;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.RETURNS_DEEP_STUBS;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.Executor;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.client.RestClient;

import com.cooksync_server.entities.RecipeImportJob;
import com.cooksync_server.entities.RecipeImportJobImage;
import com.cooksync_server.entities.Unit;
import com.cooksync_server.entities.User;
import com.cooksync_server.exceptions.RateLimitExceededException;
import com.cooksync_server.exceptions.ResourceNotFoundException;
import com.cooksync_server.exceptions.auth.UnauthorizedActionException;
import com.cooksync_server.recipeimport.ExtractedRecipe;
import com.cooksync_server.recipeimport.ImageInput;
import com.cooksync_server.recipeimport.RecipeExtractionProvider;
import com.cooksync_server.recipeimport.RobotsTxtChecker;
import com.cooksync_server.recipeimport.WebPageTextExtractor;
import com.cooksync_server.repositories.RecipeImportJobRepository;
import com.cooksync_server.repositories.UnitRepository;
import com.cooksync_server.repositories.UserRepository;
import com.dtos.request.recipe.RecipeCreateRequestDTO;
import com.dtos.request.recipeimport.RecipeImportStartRequestDTO;
import com.dtos.response.recipe.RecipeResponse;
import com.dtos.response.recipeimport.RecipeImportJobResponse;

/**
 * Unit test suite verifying recipe-import job creation (validation, per-user rate limiting), job
 * status retrieval (ownership), and the background processing pipeline (extraction success/
 * failure, unit-code resolution with a "piece" fallback, forced PRIVATE visibility, and
 * attribution) in RecipeImportServiceImp.
 *
 * @author Yaron Serlin
 * @version 1.0
 * @since 05/09/2026
 */
@ExtendWith(MockitoExtension.class)
class RecipeImportServiceTest {

    @Mock
    private RecipeImportJobRepository recipeImportJobRepository;
    @Mock
    private UserRepository userRepository;
    @Mock
    private UnitRepository unitRepository;
    @Mock
    private RecipeService recipeService;
    @Mock
    private RecipeExtractionProvider extractionProvider;
    @Mock
    private WebPageTextExtractor webPageTextExtractor;
    @Mock
    private RobotsTxtChecker robotsTxtChecker;

    /** A same-thread executor so {@code notificationExecutor.execute(...)} runs synchronously
     *  and processing completes before the test method returns. */
    private final Executor synchronousExecutor = Runnable::run;

    /** Deep-stubbed in place of the real {@code RestClient.create()} instance, so a PHOTO
     *  import's image download returns fixed bytes instead of making a real HTTP call —
     *  see {@link #setUp}. */
    private final RestClient imageDownloadClient = mock(RestClient.class, RETURNS_DEEP_STUBS);

    @InjectMocks
    private RecipeImportServiceImp service;

    @Captor
    private ArgumentCaptor<RecipeImportJob> jobCaptor;
    @Captor
    private ArgumentCaptor<RecipeCreateRequestDTO> createRequestCaptor;

    private User user;
    private Unit pieceUnit;
    private Unit gramUnit;

    @BeforeEach
    void setUp() throws Exception {
        user = new User();
        user.setId("user-1");
        user.setEmail("chef@example.com");

        pieceUnit = Unit.builder().id("unit-piece").code("piece").name("Piece").namePlural("Pieces").build();
        gramUnit = Unit.builder().id("unit-gram").code("g").name("Gram").namePlural("Grams").build();

        // Executor and imageDownloadClient are both final fields the service builds/initializes
        // itself, not constructor-settable via @InjectMocks alone since RecipeImportServiceImp's
        // constructor is generated by Lombok in declared field order - reflection keeps this
        // test independent of that ordering.
        java.lang.reflect.Field executorField = RecipeImportServiceImp.class.getDeclaredField("notificationExecutor");
        executorField.setAccessible(true);
        executorField.set(service, synchronousExecutor);

        java.lang.reflect.Field imageClientField = RecipeImportServiceImp.class.getDeclaredField("imageDownloadClient");
        imageClientField.setAccessible(true);
        imageClientField.set(service, imageDownloadClient);
        // lenient: only the PHOTO-path tests actually exercise this download call; every WEB
        // test would otherwise trip strict-stubbing's "unnecessary stubbing" check.
        org.mockito.Mockito.lenient().when(imageDownloadClient.get().uri(anyString()).retrieve().body(byte[].class))
                .thenReturn(new byte[]{1, 2, 3});
    }

    @Test
    void startImport_throwsResourceNotFound_whenUserMissing() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.empty());
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("WEB", "https://example.com/recipe", null);

        assertThrows(ResourceNotFoundException.class, () -> service.startImport(request, "chef@example.com"));
    }

    @Test
    void startImport_throwsIllegalArgument_whenWebImportMissingUrl() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("WEB", null, null);

        assertThrows(IllegalArgumentException.class, () -> service.startImport(request, "chef@example.com"));
    }

    @Test
    void startImport_throwsIllegalArgument_whenPhotoImportMissingImageUrl() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("PHOTO", null, List.of());

        assertThrows(IllegalArgumentException.class, () -> service.startImport(request, "chef@example.com"));
    }

    @Test
    void startImport_throwsIllegalArgument_whenTooManyPhotos() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        List<String> sixPhotos = List.of("u1", "u2", "u3", "u4", "u5", "u6");
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("PHOTO", null, sixPhotos);

        assertThrows(IllegalArgumentException.class, () -> service.startImport(request, "chef@example.com"));
        verify(recipeImportJobRepository, never()).save(any());
    }

    @Test
    void startImport_photoImport_buildsOrderedSourceImages() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        when(recipeImportJobRepository.countByUserIdAndCreatedAtAfter(eq("user-1"), any(LocalDateTime.class)))
                .thenReturn(0L);
        when(recipeImportJobRepository.save(any(RecipeImportJob.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));
        List<String> photoUrls = List.of("https://cdn.example.com/p1.jpg", "https://cdn.example.com/p2.jpg");
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("PHOTO", null, photoUrls);

        service.startImport(request, "chef@example.com");

        verify(recipeImportJobRepository).save(jobCaptor.capture());
        List<RecipeImportJobImage> savedImages = jobCaptor.getValue().getSourceImages();
        assertEquals(2, savedImages.size());
        assertEquals("https://cdn.example.com/p1.jpg", savedImages.get(0).getImageUrl());
        assertEquals(0, savedImages.get(0).getSortOrder());
        assertEquals("https://cdn.example.com/p2.jpg", savedImages.get(1).getImageUrl());
        assertEquals(1, savedImages.get(1).getSortOrder());
    }

    @Test
    void startImport_throwsRateLimitExceeded_whenUserAtLimit() {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        when(recipeImportJobRepository.countByUserIdAndCreatedAtAfter(eq("user-1"), any(LocalDateTime.class)))
                .thenReturn(5L);
        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("WEB", "https://example.com/recipe", null);

        assertThrows(RateLimitExceededException.class, () -> service.startImport(request, "chef@example.com"));
        verify(recipeImportJobRepository, never()).save(any());
    }

    @Test
    void startImport_savesPendingJob_andDispatchesProcessing_whenUnderLimit() throws Exception {
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));
        when(recipeImportJobRepository.countByUserIdAndCreatedAtAfter(eq("user-1"), any(LocalDateTime.class)))
                .thenReturn(0L);
        when(recipeImportJobRepository.save(any(RecipeImportJob.class)))
                .thenAnswer(invocation -> {
                    RecipeImportJob job = invocation.getArgument(0);
                    job.setId("job-1");
                    return job;
                });
        when(recipeImportJobRepository.findWithUserById("job-1")).thenAnswer(invocation -> {
            RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                    .sourceType(RecipeImportJob.SourceType.WEB).sourceUrl("https://example.com/recipe")
                    .status(RecipeImportJob.Status.PENDING).build();
            return Optional.of(job);
        });
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));
        when(robotsTxtChecker.isAllowed(anyString())).thenReturn(true);
        when(webPageTextExtractor.fetchReadableContent(anyString()))
                .thenReturn(new WebPageTextExtractor.PageContent("page text", null));
        when(extractionProvider.extractFromWebPage(anyString(), any())).thenReturn(Optional.empty());

        RecipeImportStartRequestDTO request = new RecipeImportStartRequestDTO("WEB", "https://example.com/recipe", null);
        RecipeImportJobResponse response = service.startImport(request, "chef@example.com");

        assertEquals("PENDING", response.status());
        // Saved 3 times: creating the PENDING row, the (synchronously-run) pipeline's
        // PENDING->PROCESSING transition, and its PROCESSING->FAILED transition (extraction
        // returned empty here).
        verify(recipeImportJobRepository, times(3)).save(jobCaptor.capture());
        assertEquals(RecipeImportJob.Status.FAILED, jobCaptor.getValue().getStatus());
    }

    @Test
    void getJobStatus_throwsUnauthorized_whenRequesterIsNotOwner() {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user).status(RecipeImportJob.Status.PENDING).build();
        User otherUser = new User();
        otherUser.setId("user-2");
        otherUser.setEmail("other@example.com");

        when(recipeImportJobRepository.findById("job-1")).thenReturn(Optional.of(job));
        when(userRepository.findByEmail("other@example.com")).thenReturn(Optional.of(otherUser));

        assertThrows(UnauthorizedActionException.class, () -> service.getJobStatus("job-1", "other@example.com"));
    }

    @Test
    void getJobStatus_returnsStatus_whenRequesterIsOwner() {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user).status(RecipeImportJob.Status.SUCCEEDED)
                .resultRecipeId("recipe-1").build();
        when(recipeImportJobRepository.findById("job-1")).thenReturn(Optional.of(job));
        when(userRepository.findByEmail("chef@example.com")).thenReturn(Optional.of(user));

        RecipeImportJobResponse response = service.getJobStatus("job-1", "chef@example.com");

        assertEquals("SUCCEEDED", response.status());
        assertEquals("recipe-1", response.resultRecipeId());
    }

    @Test
    void processImport_marksFailed_whenRobotsTxtDisallows() {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                .sourceType(RecipeImportJob.SourceType.WEB).sourceUrl("https://example.com/recipe")
                .status(RecipeImportJob.Status.PENDING).build();
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));
        when(robotsTxtChecker.isAllowed("https://example.com/recipe")).thenReturn(false);

        service.processImport("job-1");

        verify(recipeImportJobRepository, times(2)).save(jobCaptor.capture());
        RecipeImportJob finalState = jobCaptor.getValue();
        assertEquals(RecipeImportJob.Status.FAILED, finalState.getStatus());
        assertEquals("ROBOTS_DISALLOWED", finalState.getErrorMessage());
        verify(recipeService, never()).createRecipe(any(), anyString());
    }

    @Test
    void processImport_marksFailed_whenExtractionReturnsEmpty() throws Exception {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                .sourceType(RecipeImportJob.SourceType.WEB).sourceUrl("https://example.com/recipe")
                .status(RecipeImportJob.Status.PENDING).build();
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));
        when(robotsTxtChecker.isAllowed(anyString())).thenReturn(true);
        when(webPageTextExtractor.fetchReadableContent(anyString()))
                .thenReturn(new WebPageTextExtractor.PageContent("not a recipe", null));
        when(extractionProvider.extractFromWebPage(anyString(), any())).thenReturn(Optional.empty());

        service.processImport("job-1");

        verify(recipeImportJobRepository, times(2)).save(jobCaptor.capture());
        assertEquals(RecipeImportJob.Status.FAILED, jobCaptor.getValue().getStatus());
        verify(recipeService, never()).createRecipe(any(), anyString());
    }

    @Test
    void processImport_marksFailed_withDistinctCode_whenExtractionServiceItselfFails() throws Exception {
        // e.g. Gemini's free-tier daily quota exhausted, or a transient outage — distinct from
        // the model genuinely determining the content isn't a recipe.
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                .sourceType(RecipeImportJob.SourceType.WEB).sourceUrl("https://example.com/recipe")
                .status(RecipeImportJob.Status.PENDING).build();
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));
        when(robotsTxtChecker.isAllowed(anyString())).thenReturn(true);
        when(webPageTextExtractor.fetchReadableContent(anyString()))
                .thenReturn(new WebPageTextExtractor.PageContent("recipe text", null));
        when(extractionProvider.extractFromWebPage(anyString(), any()))
                .thenThrow(new com.cooksync_server.recipeimport.ExtractionServiceException("quota exhausted", null));

        service.processImport("job-1");

        verify(recipeImportJobRepository, times(2)).save(jobCaptor.capture());
        assertEquals(RecipeImportJob.Status.FAILED, jobCaptor.getValue().getStatus());
        assertEquals("EXTRACTION_SERVICE_UNAVAILABLE", jobCaptor.getValue().getErrorMessage());
        verify(recipeService, never()).createRecipe(any(), anyString());
    }

    @Test
    void processImport_resolvesUnknownUnitCode_toPieceFallback_andCreatesPrivateRecipe() throws Exception {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                .sourceType(RecipeImportJob.SourceType.WEB).sourceUrl("https://example.com/recipe")
                .status(RecipeImportJob.Status.PENDING).build();
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit, gramUnit));
        when(robotsTxtChecker.isAllowed(anyString())).thenReturn(true);
        when(webPageTextExtractor.fetchReadableContent(anyString()))
                .thenReturn(new WebPageTextExtractor.PageContent("recipe text", "https://example.com/cover.jpg"));

        ExtractedRecipe extracted = new ExtractedRecipe(
                "Test Recipe", "A description.", "EASY", 10, 20, 4,
                List.of(
                        new ExtractedRecipe.ExtractedIngredient("flour", new java.math.BigDecimal("200"), "g"),
                        new ExtractedRecipe.ExtractedIngredient("eggs", new java.math.BigDecimal("2"), "not-a-real-unit")),
                List.of("Mix.", "Bake."));
        when(extractionProvider.extractFromWebPage(anyString(), any())).thenReturn(Optional.of(extracted));
        when(unitRepository.findByCodeIgnoreCase("g")).thenReturn(Optional.of(gramUnit));
        when(unitRepository.findByCodeIgnoreCase("not-a-real-unit")).thenReturn(Optional.empty());
        when(unitRepository.findByCodeIgnoreCase("piece")).thenReturn(Optional.of(pieceUnit));

        RecipeResponse created = new RecipeResponse("recipe-1", null, "Test Recipe", "EASY", "PRIVATE",
                10, 20, 4, 0, null, List.of(), "2026-01-01T00:00:00", null, List.of(), java.util.Set.of(),
                List.of(), null, List.of(), false, null, null);
        when(recipeService.createRecipe(any(RecipeCreateRequestDTO.class), eq("chef@example.com"))).thenReturn(created);

        service.processImport("job-1");

        verify(recipeService).createRecipe(createRequestCaptor.capture(), eq("chef@example.com"));
        RecipeCreateRequestDTO createRequest = createRequestCaptor.getValue();
        assertEquals("PRIVATE", createRequest.visibility());
        assertEquals(2, createRequest.ingredients().size());
        assertEquals("unit-gram", createRequest.ingredients().get(0).unitId());
        assertEquals("unit-piece", createRequest.ingredients().get(1).unitId());

        verify(recipeService).setSourceAttribution(eq("recipe-1"), eq("https://example.com/recipe"), anyString());
        verify(recipeImportJobRepository, times(2)).save(jobCaptor.capture());
        assertEquals(RecipeImportJob.Status.SUCCEEDED, jobCaptor.getValue().getStatus());
        assertEquals("recipe-1", jobCaptor.getValue().getResultRecipeId());
    }

    @Test
    void processImport_photoImport_singlePhoto_createsPrivateRecipe_withPhotoAttribution() throws Exception {
        RecipeImportJob job = jobWithPhotos(List.of("https://cdn.example.com/p1.jpg"));
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));

        ExtractedRecipe extracted = new ExtractedRecipe(
                "Grandma's Cookies", "", "EASY", 10, 15, 4,
                List.of(new ExtractedRecipe.ExtractedIngredient("flour", new java.math.BigDecimal("2"), "piece")),
                List.of("Mix.", "Bake."));
        when(extractionProvider.extractFromImages(any(), any())).thenReturn(Optional.of(extracted));
        when(unitRepository.findByCodeIgnoreCase("piece")).thenReturn(Optional.of(pieceUnit));

        RecipeResponse created = new RecipeResponse("recipe-1", null, "Grandma's Cookies", "EASY", "PRIVATE",
                10, 15, 4, 0, null, List.of(), "2026-01-01T00:00:00", null, List.of(), java.util.Set.of(),
                List.of(), null, List.of(), false, null, null);
        when(recipeService.createRecipe(any(RecipeCreateRequestDTO.class), eq("chef@example.com"))).thenReturn(created);

        service.processImport("job-1");

        verify(recipeService).createRecipe(createRequestCaptor.capture(), eq("chef@example.com"));
        assertEquals("https://cdn.example.com/p1.jpg", createRequestCaptor.getValue().primaryImageUrl());
        verify(recipeService).setSourceAttribution(eq("recipe-1"), eq("https://cdn.example.com/p1.jpg"), eq("Imported from a photo"));
    }

    @Test
    void processImport_photoImport_multiplePhotos_passesAllImages_toExtractionProvider_andAttributesFirstPhoto() throws Exception {
        RecipeImportJob job = jobWithPhotos(List.of(
                "https://cdn.example.com/p1.jpg", "https://cdn.example.com/p2.jpg", "https://cdn.example.com/p3.jpg"));
        when(recipeImportJobRepository.findWithUserById("job-1")).thenReturn(Optional.of(job));
        when(unitRepository.findAll()).thenReturn(List.of(pieceUnit));

        ExtractedRecipe extracted = new ExtractedRecipe(
                "Handwritten Soup", "", "EASY", 5, 30, 6, List.of(), List.of("Simmer."));
        when(extractionProvider.extractFromImages(any(), any())).thenReturn(Optional.of(extracted));

        RecipeResponse created = new RecipeResponse("recipe-2", null, "Handwritten Soup", "EASY", "PRIVATE",
                5, 30, 6, 0, null, List.of(), "2026-01-01T00:00:00", null, List.of(), java.util.Set.of(),
                List.of(), null, List.of(), false, null, null);
        when(recipeService.createRecipe(any(RecipeCreateRequestDTO.class), eq("chef@example.com"))).thenReturn(created);

        @SuppressWarnings("unchecked")
        ArgumentCaptor<List<ImageInput>> imagesCaptor = ArgumentCaptor.forClass(List.class);

        service.processImport("job-1");

        verify(extractionProvider).extractFromImages(imagesCaptor.capture(), any());
        assertEquals(3, imagesCaptor.getValue().size());

        verify(recipeService).createRecipe(createRequestCaptor.capture(), eq("chef@example.com"));
        assertEquals("https://cdn.example.com/p1.jpg", createRequestCaptor.getValue().primaryImageUrl());
        verify(recipeService).setSourceAttribution(eq("recipe-2"), eq("https://cdn.example.com/p1.jpg"), eq("Imported from photos"));
    }

    /**
     * Builds a PHOTO {@link RecipeImportJob} with the given source photo URLs already attached in
     * order, matching how {@link RecipeImportServiceImp#startImport} assembles one.
     */
    private RecipeImportJob jobWithPhotos(List<String> photoUrls) {
        RecipeImportJob job = RecipeImportJob.builder().id("job-1").user(user)
                .sourceType(RecipeImportJob.SourceType.PHOTO)
                .status(RecipeImportJob.Status.PENDING).build();
        for (int i = 0; i < photoUrls.size(); i++) {
            job.getSourceImages().add(RecipeImportJobImage.builder()
                    .job(job).imageUrl(photoUrls.get(i)).sortOrder(i).build());
        }
        return job;
    }

    private static String findUnitCodeById(RecipeCreateRequestDTO request, String unitId) {
        return request.ingredients().stream()
                .filter(i -> i.unitId().equals(unitId))
                .findFirst()
                .map(i -> unitId.equals("unit-gram") ? "g" : "piece")
                .orElse(null);
    }
}
